format_version: 3
pipelines:
  gradle-cache:
    group: repo-team
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build-cache-on-an-agent:
          approval: manual
          tasks:
            - exec:
                command: ./build_cache.sh
            - exec:
                command: pwd
            - exec:
                command: ls
                arguments:
                  - "-ltr"
                  - .gradle-readonly-cache
      - build-cache-on-all-agents:
          approval: manual
          run_instances: all
          tasks:
            - exec:
                command: ./build_cache.sh
